### ISSUE TITLE
Add Rubocop example

### ISSUE THREAD

**Issue by sunny** [KissKissBankBank/fashion_police#5]
Generic `.rubocop.yml` file we could include:

```yml
AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

# Do not sort gems in Gemfile, since we are grouping them by functionality.
Bundler/OrderedGems:
  Enabled: false

# Trailing commas are required on multiline method arguments.
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# Trailing commas are required in multiline arrays and hashes.
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

# Allow indenting multiline chained operations.
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Limit method length (default is 10).
Metrics/MethodLength:
  Max: 15

# Do not require `# frozen_string_literal: true` at the top of every file.
FrozenStringLiteralComment:
  Enabled: false

# Allow ASCII comments (e.g "…").
Style/AsciiComments:
  Enabled: false

# Do not comment the class we create, since the name should be self explanatory.
Documentation:
  Enabled: false

# Do not verify the length of the blocks in specs.
Metrics/BlockLength:
  Exclude:
    - spec/**/*

# Allow indenting multiline chained operations.
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
```
